services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: svelte-dev
    ports:
      - "5173:5173"  # Default Vite port
    volumes:
      - .:/app
      - /app/node_modules  # This prevents local node_modules from mounting
    environment:
      - NODE_ENV=development
      - HOST=0.0.0.0
      - VITE_ALLOW_ORIGIN=true
      - VITEST=true  # Add this for Vitest
    working_dir: /app
    command: npm run dev -- --host 0.0.0.0
    stdin_open: true
    tty: true

  test:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: svelte-test
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=test
      - VITEST=true
    working_dir: /app
    command: npm run test:watch
